[project]
name = "lagrange-python"
version = "0.0.1"
description = "An Python Implementation of NTQQ PC Protocol"
authors = [
    {name="linwenxuan05"},
    {name="wyapx"},
]
dependencies = [
    "cryptography>=39.0.2",
    "typing-extensions"
]
requires-python = ">=3.8"

[tool.pdm]
distribution = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
